# Generated by Django 5.0.1 on 2025-12-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlysummary',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statechange',
            name='status',
            field=models.IntegerField(choices=[(0, '🔴 went Offline'), (1, '🟢 went Online')]),
        ),
    ]
