# Generated by Django 5.0.1 on 2025-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_hourlysummary_synced_alter_statechange_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_start', models.DateTimeField()),
                ('downtime_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_downtimes',
                'ordering': ['-downtime_start'],
            },
        ),
    ]
