# Generated by Django 5.0.1 on 2025-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_agentdowntime'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdowntime',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
